service: planner-api

provider:
  name: aws
  
functions:
  PlannerApi:
    name: PlannerAPi
    handler: PlannerApi::PlannerApi.LambdaEntryPoint::FunctionHandlerAsync
    role: lambdaExecutionRole
    environment:
      CONNECTION_STRING: Host=${ssm:/planner-api/production/connection-string}
    events:
      - http:
          path: /{proxy+}
          method: ANY
          # authorizer:
          #   arn: ${ssm:/api-authenticator/${self:provider.stage}/arn}
          #   type: request
          #   resultTtlInSeconds: 0
          #   identitySource: method.request.header.Authorization
          #   managedExternally: true
          cors:
            origin: '*' # need to update
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true