# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  win: circleci/windows@2.4

  executors:
  docker-dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-and-test:
    machine: true 
    steps:
      - checkout
      - run:
          working_directory: ~/project/PlannerApi
          name: Build
          command: |
            docker-compose build test
      - run:
          working_directory: ~/project/PlannerApi
          name: Run tests
          command: |
            docker-compose run test

  deploy-to-production:
    steps:
      # - *attach_workspace
      - checkout
      - setup_remote_docker
      - run:
          name: Install Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_14.x | bash -
            apt-get update && apt-get install -y nodejs
      - run:
          name: Install serverless CLI
          command: npm i -g serverless
      - run:
          name: Build lambda
          command: |
            cd ./PlannerApi/
            chmod +x ./build.sh
            ./build.sh
      - run:
          name: Deploy lambda
          command: |
            cd ./PlannerApi/
            sls deploy --stage production --conceal


workflows:
  test-and-deploy:
    jobs: 
        - build-and-test
        # - migrate-database:
        #     requires:
        #       - terraform-init-and-apply
        #     filters:
        #       only: main
        - deploy-to-production
            requires:
              - build-and-test
            # filters:
              # only: main

